services:
  db:
    image: postgres:17
    container_name: todo-db
    restart: "no"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
volumes:
  todo_pg_data:
    driver: local
