services:
  db:
    image: postgres:17
    container_name: duties-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - duties_pg_data:/var/lib/postgresql/data
      - ./src/db:/docker-entrypoint-initdb.d
volumes:
  duties_pg_data:
    driver: local
