CREATE TABLE todos (
    id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    is_completed BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() CURRENT_TIMESTAMP NOT NULL
)